# Generated by Django 5.2 on 2025-07-25 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMBCChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_body', models.CharField(max_length=100)),
                ('piston_trunnion', models.CharField(max_length=100)),
                ('adjusting_tube', models.CharField(max_length=100)),
                ('plunger_spring', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BogieChecksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogie_frame_condition', models.CharField(max_length=100)),
                ('bolster', models.CharField(max_length=100)),
                ('bolster_suspension_bracket', models.CharField(max_length=100)),
                ('lower_spring_seat', models.CharField(max_length=100)),
                ('axle_guide', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BogieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bogie_no', models.CharField(max_length=50)),
                ('maker_year_built', models.CharField(max_length=100)),
                ('incoming_div_and_date', models.CharField(max_length=100)),
                ('deficit_components', models.CharField(max_length=255)),
                ('date_of_ioh', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=50)),
                ('inspection_by', models.CharField(max_length=100)),
                ('inspection_date', models.DateField()),
                ('bmbc_checksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.bmbcchecksheet')),
                ('bogie_checksheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.bogiechecksheet')),
                ('bogie_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.bogiedetails')),
            ],
        ),
    ]
